export const ImageDetail = [
    {
      id: 0,
      image: require("../../images/food_img_1.jpg"),
      name: "Mahesh",
      description: "All happiness depends on a leisurrely breakfast",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$34.00",
          calories: 330,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Raju",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$35.50",
          calories: 200,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Suresh",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$34.90",
          calories: 730,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Kamal",
          description: "Green & Fresh, just like a sunny day",
          prize: "$35.00",
          calories: 630,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Mahendra",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$31.50",
          calories: 450,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Ravi",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$90.50",
          calories: 410,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Shark fillet with lemon",
          description: "have a big dinner with friends and talk about life",
          prize: "$45.50",
          calories: 530,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
    {
      id: 1,
      image: require("../../images/food_img_2.jpg"),
      name: "Mahenra",
      description: "As long as there was coffee in the world, how bad could things be?",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Mahesh",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$95.50",
          calories: 630,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Mahendra",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$34.00",
          calories: 830,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Ravi",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$544.00",
          calories: 230,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Kamal",
          description: "Green & Fresh, just like a sunny day",
          prize: "$35.50",
          calories: 330,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Jaswant",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$35.50",
          calories: 460,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Krishan",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$466.00",
          calories: 345,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Ravi",
          description: "have a big dinner with friends and talk about life",
          prize: "$466.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
    {
      id: 2,
      image: require("../../images/food_img_3.jpg"),
      name: "Kamal",
      description: "I am not a vegetarian! i am a dessertarian!",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Wine with salads",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$96.00",
          calories: 630,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Coffee",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$466.00",
          calories: 420,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Fried eggs with tomatos",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$466.00",
          calories: 630,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Fried eggs with tomatos",
          description: "Green & Fresh, just like a sunny day",
          prize: "$466.00",
          calories: 630,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Wine with salads",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$466.00",
          calories: 4560,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$46.00",
          calories: 560,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Shark fillet with lemon",
          description: "have a big dinner with friends and talk about life",
          prize: "$466.00",
          calories: 530,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
    {
      id: 3,
      image: require("../../images/food_img_4.jpg"),
      name: "Ravi",
      description: "Either given me more wine or leave me alone",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Wine with salads",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$466.00",
          calories: 730,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Fried eggs with tomatos",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$466.00",
          calories: 350,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Dessert",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$70.90",
          calories: 330,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Wine with salads",
          description: "Green & Fresh, just like a sunny day",
          prize: "$466.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Shark fillet with lemon",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Beef Steak Breakfast",
          description: "have a big dinner with friends and talk about life",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
    {
      id: 4,
      image: require("../../images/food_img_5.jpg"),
      name: "Vishnu",
      description: "Green & Fresh, just like a sunny day",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Fried eggs with tomatos",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Fried eggs with tomatos",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Dessert",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Fried eggs with tomatos",
          description: "Green & Fresh, just like a sunny day",
          prize: "$78.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Wine with salads",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Beef Steak Breakfast",
          description: "have a big dinner with friends and talk about life",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
    {
      id: 5,
      image: require("../../images/food_img_6.jpg"),
      name: "Krishan",
      description: "have a big dinner with friends and talk about life",
      allFood: [
        {
          cid: 0,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 1,
          image: require("../../images/food_img_2.jpg"),
          name: "Coffee",
          description: "As long as there was coffee in the world, how bad could things be?",
          prize: "$466.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 2,
          image: require("../../images/food_img_3.jpg"),
          name: "Fried eggs with tomatos",
          description: "I am not a vegetarian! i am a dessertarian!",
          prize: "$70.90",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 3,
          image: require("../../images/food_img_5.jpg"),
          name: "Beef Steak Breakfast",
          description: "Green & Fresh, just like a sunny day",
          prize: "$466.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 4,
          image: require("../../images/food_img_1.jpg"),
          name: "Wine with salads",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$66.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 5,
          image: require("../../images/food_img_1.jpg"),
          name: "Beef Steak Breakfast",
          description: "All happiness depends on a leisurrely breakfast",
          prize: "$466.00",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
        {
          cid: 6,
          image: require("../../images/food_img_6.jpg"),
          name: "Shark fillet with lemon",
          description: "have a big dinner with friends and talk about life",
          prize: "$35.50",
          calories: 430,
          product_img: [
            require("../../images/food_img_1.jpg"),
            require("../../images/food_img_2.jpg"),
            require("../../images/food_img_3.jpg"),
            require("../../images/food_img_4.jpg"),
            require("../../images/food_img_5.jpg"),
            require("../../images/food_img_6.jpg"),
          ],
        },
      ],
    },
  ]
  